server:
  port: 8081
  servlet:
    context-path: /api  # endpoints start with /api/...

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=ecommerce
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none       # we manage tables manually
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ecommerce

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 12MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    active: dev   # ðŸ‘ˆ change to 'prod' when deploying

# swagger
springdoc:
  api-docs:
    use-fqn: true
    writer-with-default-pretty-printer: true
    default-produces-media-type: application/json
    enabled: true
    path: /v3/api-docs
    resolve-schema-properties: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret: "u8Kd9sFJ3lP9q2Qz7W3Ny9Ypw1BzXUe0IFhXPLnKEHQ="
  expiration: 86400000   # 1 hour in ms


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
